### ISSUE TITLE
[META] Plan

### ISSUE THREAD

**Issue by moul** [gnoverse/acs#1]
# MVP

* [ ] Prepare an initial challenge
  * [ ] Prepare its brief
  * [ ] Prepare the review system (unit tests?)
* [ ] Prepare a list of open questions
* [ ] Develop a website where people can submit an application
  * [ ] Propose a solution to a challenge
  * [ ] Reply to questions
* [ ] Automate the review of the challenge

# Bonus

* [ ] Alert the staff about new applications
* [ ] Support multiple challenges
* [ ] Support anonymous applications
* [ ] Anti-bruteforce, anti-spam
* [ ] Anti-plagiarism
* [ ] Link with a chain, i.e. mint a token-gated badge for winners

**Comment by zivkovicmilos** [comment]
Following this issue 👀 

How big of a priority is this platform, currently?

**Comment by ajnavarro** [comment]
Following too :eyes:
